### ISSUE TITLE
'window.isOpenInEditorEnabled is not a function' after updating with homebrew

### ISSUE THREAD

**Issue by timkuilman** [jhen0409/react-native-debugger#420] opened 2019-10-22 13:36 UTC
Hi, 

The update function of the react-native-debugger did not work properly so I decided to re-install react-native-debugger with homebrew. After upgrading I can't get the debugger to work properly again. The console gives the following output:

```
bundle.js:10 Uncaught SyntaxError: Invalid or unexpected token
VM108:1 Uncaught TypeError: window.isOpenInEditorEnabled is not a function
    at <anonymous>:1:8
    at WebFrame.<computed> (/Applications/React Native Debugger.app/Contents/Resources/electron.asar/renderer/api/web-frame.js:64)
    at WebFrame.executeJavaScript (/Applications/React Native Debugger.app/Contents/Resources/electron.asar/common/api/deprecate.js:114)
    at /Applications/React Native Debugger.app/Contents/Resources/electron.asar/renderer/web-frame-init.js:11
    at /Applications/React Native Debugger.app/Contents/Resources/electron.asar/renderer/ipc-renderer-internal-utils.js:7
    at new Promise (<anonymous>)
    at EventEmitter.<anonymous> (/Applications/React Native Debugger.app/Contents/Resources/electron.asar/renderer/ipc-renderer-internal-utils.js:7)
    at EventEmitter.emit (events.js:200)
    at Object.onMessage (/Applications/React Native Debugger.app/Contents/Resources/electron.asar/renderer/init.js:42)
VM108:1 Uncaught TypeError: window.isOpenInEditorEnabled is not a function
    at <anonymous>:1:8
    at WebFrame.<computed> (/Applications/React Native Debugger.app/Contents/Resources/electron.asar/renderer/api/web-frame.js:64)
    at WebFrame.executeJavaScript (/Applications/React Native Debugger.app/Contents/Resources/electron.asar/common/api/deprecate.js:114)
    at /Applications/React Native Debugger.app/Contents/Resources/electron.asar/renderer/web-frame-init.js:11
    at /Applications/React Native Debugger.app/Contents/Resources/electron.asar/renderer/ipc-renderer-internal-utils.js:7
    at new Promise (<anonymous>)
    at EventEmitter.<anonymous> (/Applications/React Native Debugger.app/Contents/Resources/electron.asar/renderer/ipc-renderer-internal-utils.js:7)
    at EventEmitter.emit (events.js:200)
    at Object.onMessage (/Applications/React Native Debugger.app/Contents/Resources/electron.asar/renderer/init.js:42)
VM108:1 Uncaught TypeError: window.isOpenInEditorEnabled is not a function
    at <anonymous>:1:8
    at WebFrame.<computed> (/Applications/React Native Debugger.app/Contents/Resources/electron.asar/renderer/api/web-frame.js:64)
    at WebFrame.executeJavaScript (/Applications/React Native Debugger.app/Contents/Resources/electron.asar/common/api/deprecate.js:114)
    at /Applications/React Native Debugger.app/Contents/Resources/electron.asar/renderer/web-frame-init.js:11
    at /Applications/React Native Debugger.app/Contents/Resources/electron.asar/renderer/ipc-renderer-internal-utils.js:7
    at new Promise (<anonymous>)
    at EventEmitter.<anonymous> (/Applications/React Native Debugger.app/Contents/Resources/electron.asar/renderer/ipc-renderer-internal-utils.js:7)
    at EventEmitter.emit (events.js:200)
    at Object.onMessage (/Applications/React Native Debugger.app/Contents/Resources/electron.asar/renderer/init.js:42)
VM109:1 Uncaught TypeError: window.checkWindowInfo is not a function
    at <anonymous>:1:8
    at WebFrame.<computed> (/Applications/React Native Debugger.app/Contents/Resources/electron.asar/renderer/api/web-frame.js:64)
    at WebFrame.executeJavaScript (/Applications/React Native Debugger.app/Contents/Resources/electron.asar/common/api/deprecate.js:114)
    at /Applications/React Native Debugger.app/Contents/Resources/electron.asar/renderer/web-frame-init.js:11
    at /Applications/React Native Debugger.app/Contents/Resources/electron.asar/renderer/ipc-renderer-internal-utils.js:7
    at new Promise (<anonymous>)
    at EventEmitter.<anonymous> (/Applications/React Native Debugger.app/Contents/Resources/electron.asar/renderer/ipc-renderer-internal-utils.js:7)
    at EventEmitter.emit (events.js:200)
    at Object.onMessage (/Applications/React Native Debugger.app/Contents/Resources/electron.asar/renderer/init.js:42)

```

Can this be caused by the new Electron releases? Within the last 24 hours v6.1.0, v7.0.0 and the first nightly for v8 were released. 

React Native Debugger app version: 0.10.2
Platform: IOS
Is real device of platform:  
Operating System: MacOS

**Comment by jhen0409** [comment] 2019-10-23 00:58
Duplicate of #410.

**Closed by jhen0409** 2019-10-23 00:58 UTC
