### ISSUE TITLE
Apollo devtools does not show up

### ISSUE THREAD

**Issue by dusan-dragon** [jhen0409/react-native-debugger#331] opened 2019-03-04 09:58 UTC
React Native Debugger app version: [0.9.7]
React Native version: [0.57.1]
Platform: [Android]
Is real device of platform: [No - emulator]
Operating System: [Linux]
"apollo-client": "2.4.12"

It is strange, because I can see that apollo client is initialized (it exists on self object):
![debugger](https://user-images.githubusercontent.com/45170274/53725479-5ed63f00-3e6c-11e9-99ae-04f2c0990b0b.png)

**Comment by TheDeveloperTom** [comment] 2019-05-01 10:01
The same thing

**Comment by TheDeveloperTom** [comment] 2019-05-01 10:21
The problem is resolved. 

Open the extensions settings in the Chrome browser, find the Apollo DevTools extension, and in the settings of the extension enable something like "Allow open local ...".

Hope it'll help.

**Comment by Gongreg** [comment] 2019-05-13 12:45
@TheDeveloperTom did the solution really work for you? If you disable the option does it stop working again? I am not sure why you have this specific issue.

**Comment by jforaker** [comment] 2019-05-15 20:16
First make sure you have all the latest per docs. And then for me I had to do a form of "manual reset" with the tabs to get it to show. 
1. in the React Native Debugger menu > View
2. Toggle Developer tools (twice)  
![image](https://user-images.githubusercontent.com/2042031/57806222-af9bcb00-772c-11e9-947a-ae6d8bebc811.png)

**Comment by Gongreg** [comment] 2019-05-27 04:12
Hey,
I've created a PR for apollo-dev-tools https://github.com/apollographql/apollo-client-devtools/pull/203 that will solve a lot of issues for users (they don't see apollo tab appearing). Sadly the maintainers of apollo-dev-tools have quite abandoned it for now.

**Comment by Gongreg** [comment] 2019-06-03 03:37
The PR for apollo dev tools was merged and released. So I am closing this issue for now.

**Closed** 2019-06-03 03:36 UTC
Labels: integration/apollo-client-devtools
