### ISSUE TITLE
Unsupported DevTools backend version - 

### ISSUE THREAD

**Issue by vishnuc** [jhen0409/react-native-debugger#627] opened 2021-07-05 18:25 UTC
HI , I use Expo React native

I am using  react-native": "0.63.4", and react native debugger version - v0.11.9

`You are running react-devtools version 4.13.4-51ebccc374.
`
To fix this, downgrade the DevTools NPM package:
This requires bridge protocol version 1. However the current backend version uses bridge protocol version 0

`npm i -g react-devtools@"<4.11.0"
`

I installed it globally and I even checked list of global npm packages and react-devtools@4.10.4 is installed correctly , but still dev tools is showing 4.13

and even in my expo project I removed devtools , installed react-devtools@4.10.4  , I still get the same error .. I even added  react-devtools@4.10.4  in package-lock. .. I did same with 4.13 , still I got same error.

**Comment by Wiiktor22** [comment] 2021-07-06 06:57
Hi,

I have the same problem. I have searched through the docs, but as you said - nothing helps me neither...

I have globally installed `react-devtools@4.10.4`, not in my project and this solution does not help.

I'm using an expo sdk 39 and react-native-debugger - v0.11.9

**Comment by vishnuc** [comment] 2021-07-06 07:15
I have downgraded to v 0.11.8 and it works fine..

**Comment by N1ghtly** [comment] 2021-07-06 08:57
Same problem here. Downgrading with brew is a mess...

**Comment by jhen0409** [comment] 2021-07-07 06:41
Duplicate of #620. Please see the release note or documentation.

**Closed by jhen0409** 2021-07-07 06:41 UTC

**Comment by vishnuc** [comment] 2021-07-07 08:55
I have the problem even after referring the documenation
