### ISSUE TITLE
Connections to debugger-proxy timed out.

### ISSUE THREAD

**Issue by martinezguillaume** [jhen0409/react-native-debugger#72] opened 2017-05-09 13:53 UTC
React Native version: 0.43
Platform: iOS & Android
Is real device of platform: No
Operating System: macOS

Hello, I have this error pretty often. When I have it, I must stop debug mode et restart it to make it works again, what's the problem ? (I'm using expo SDK 16, I didn't have this problem with SDK 15)

![image](https://cloud.githubusercontent.com/assets/17292331/25854267/b32c0330-34cf-11e7-99a9-fa8909f730b5.png)

**Comment by jhen0409** [comment] 2017-05-10 20:18
It's detached exp project? I can't reproduce it 😔, is this issue similar to #32?

**Comment by martinezguillaume** [comment] 2017-05-11 15:24
It's not a detached project and yes, it's the same thing as this issue !

**Comment by spencewine** [comment] 2017-05-19 14:47
you need to change localhost to your ip address in your WebSocketExecutor.m file:

http://facebook.github.io/react-native/releases/0.44/docs/debugging.html#debugging-on-a-device-with-chrome-developer-tools

**Comment by martinezguillaume** [comment] 2017-05-24 12:22
Always the same error, it's very annoying

**Comment by beeant** [comment] 2017-07-18 14:13
same thing for me.

**Comment by georgewwindsor** [comment] 2017-08-09 17:37
I am additionally experiencing this issue, and its very difficult to work through.

**Comment by jhen0409** [comment] 2017-08-10 03:31
I think it's React Native issue because it related to problem of app connecting to packager's debugger proxy ([issues](https://github.com/facebook/react-native/issues?utf8=✓&q=debugger-proxy%20timed%20out%20)). I was experienced this when I do Xcode build, but can't reproduce in newer versions. (Currently I'm using RN 0.45)

Close this because duplicate of #32.

**Closed by jhen0409** 2017-08-10 03:31 UTC
