### ISSUE TITLE
No longer able to preview network response bodies after update to 0.6.0

### ISSUE THREAD

**Issue by fossage** [jhen0409/react-native-debugger#56] opened 2017-03-15 18:41 UTC
After the recent update to v0.6.0 I can no longer see the preview or raw response body for network responses in the network tab.  I can still see all of the request and response headers being logged, but as far as response bodies go, I just see the message, 'This request has no preview available.'  in both the 'Preview' and 'Response' tabs.

I have confirmed that, by re-installing v0.5.6, I can once again see the response bodies.  If it is of any help, I am using the snippet from the documentation to enable network logging, namely:

`global.XMLHttpRequest = global.originalXMLHttpRequest ?
  global.originalXMLHttpRequest :
  global.XMLHttpRequest;
global.FormData = global.originalFormData ?
  global.originalFormData :
  global.FormData;`

That aside, this tool is great.  Thanks for making it 👍 

React Native version: 0.41.2
Platform: iOS
Is real device of platform: No
Operating System: macOSX

**Comment by jhen0409** [comment] 2017-03-16 08:43
I can reproduce it with `fetch`, I think it's related to `fetch` polyfill (`whatwg-fetch`), as I confirmed the following solutions works fine:

* Use `XMLHttpRequest` directly
* [axios](https://github.com/mzabriskie/axios)

I'll investigate it, thanks!

**Comment by jhen0409** [comment] 2017-03-16 20:07
It seems like related to [Blob](https://github.com/github/fetch/blob/1.1/fetch.js#L454-L456), the network inspect works fine when I remove `blob` response type, this problem seems to start with some Chrome version ([v0.6.0](https://github.com/jhen0409/react-native-debugger/releases/tag/v0.6.0) have updated Chrome version).

I think we can just delete `window.Blob` in debugger worker because currently react-native is not supported it, I'll do this.

**Comment by jhen0409** [comment] 2017-03-17 04:52
It should fixed by https://github.com/jhen0409/react-native-debugger/commit/c1bcb6ffeb5bba7174a7a4c7a2c1bc1b3d27141b and published as [`v0.6.1`](https://github.com/jhen0409/react-native-debugger/releases/tag/v0.6.1).

**Closed by jhen0409** 2017-03-17 04:52 UTC
Labels: bug

**Comment by chj-damon** [comment] 2020-03-03 10:22
it happened again. 
react-native-debugger version: 0.9.9
react-native version: 0.61.5

**Comment by chj-damon** [comment] 2020-03-03 10:24
I've already add this code in app.js
```js
global.XMLHttpRequest = global.originalXMLHttpRequest || global.XMLHttpRequest;
global.FormData = global.originalFormData || global.FormData;

if (window.FETCH_SUPPORT) {
  window.FETCH_SUPPORT.blob = false;
} else {
  global.Blob = global.originalBlob || global.Blob;
  global.FileReader = global.originalFileReader || global.FileReader;
}
```

**Comment by nenjamin2405** [comment] 2020-03-04 07:19
I'm having the same problem, cannot open the Apollo Tab either, the Apollo Dev Tool appears and disappears immediately

**Comment by darkbasic** [comment] 2020-03-05 07:46
Same here, I confirm the issue with react-native-debugger 0.10.6 and react-native 0.61.5

**Comment by darkbasic** [comment] 2020-03-05 08:12
I forgot to specify that it breaks network requests alltogether, with the following error:

```json
{
  "graphQLErrors": [],
  "networkError": {
    "name": "ServerParseError",
    "response": {
      "type": "default",
      "status": 200,
      "ok": true,
      "statusText": "OK",
      "headers": {
        "map": {
          "access-control-allow-origin": "*",
          "connection": "keep-alive",
          "content-length": "130",
          "content-type": "application/json; charset=utf-8",
          "date": "Thu, 05 Mar 2020 08:10:37 GMT",
          "etag": "W/\"82-Ur9iysCnuu8dKhUI0luIROzWyMg\"",
          "x-powered-by": "Express"
        }
      },
      "url": "http://192.168.1.49:4000/graphql",
      "_bodyInit": {},
      "_bodyText": "[object Blob]",
      "bodyUsed": true
    },
    "statusCode": 200,
    "bodyText": "[object Blob]"
  },
  "message": "Network error: Unexpected token o in JSON at position 1"
}
```

**Comment by bclynch** [comment] 2020-04-13 00:49
Noticing same issue myself outlined by darkbasic. Turning off network debugging allows the apollo tab to work

**Comment by darkbasic** [comment] 2020-04-19 08:37
@bclynch unfortunately I still get the very same error with react-native-debugger 0.11.1 and disable cache (which is by default in latest version).

**Comment by darkbasic** [comment] 2020-04-19 08:40
@jhen0409 can you please reopen this?

**Comment by gavin7gomes** [comment] 2024-03-19 21:00
Facing the same problem once again using **fetch** with **react-native-debugger version: v0.14.0** and **react-native version: 0.72.5**.
I can see all of the request and response headers being logged, but not the network responses, I just see the message, 'This request has no preview available.' in both the 'Preview' and 'Response' tab
