### ISSUE TITLE
[IOS] Can not connect React Native Debugger when run with Hermes

### ISSUE THREAD

**Issue by JameFreshket** [jhen0409/react-native-debugger#755] opened 2023-02-28 04:38 UTC
React Native Debugger app version: 0.13
React Native version: 0.71.3
Platform: iOS
Is real device of platform: No
Operating System: macOS

Can not connect react-native-debugger with Hermes in React Native CLI, Please help me to find solution or workaround?

**Comment by daviaugustos** [comment] 2023-03-02 00:44
Same issue here. I tried a workaround [(Open Debugger in iOS simulator not working in RN 0.70.0 #34615)](https://github.com/facebook/react-native/issues/34615) found at react-native repo, disabling hermes temporarily, but how I'm using the new Turbo Modules arch is not possible to do that. 
<img width="268" alt="image" src="https://user-images.githubusercontent.com/20953743/222300967-e5ec0a22-70fe-4a93-a40e-0a57f5c0df77.png">

**Comment by NBROKN** [comment] 2023-03-02 14:36
I had the same issue and for other reasons i went with a dev build, and since i had sdk48, remote debugger was not an option, i tried to downgrade to sdk47, then the reanimated library didn't work and i read in expo doc that even if it did, it wont work with remote debugger. Since i needed that reanimated library, i went back to sdk48 and for some reason, now i have remote debugger option in app dev menu and just confirmed that react native debugger fully works. Go with a dev build and see if it works for you.

That's my 2cents that i still cant make sense of.

**Comment by MrNaughtZero** [comment] 2023-03-03 21:42
I too had this issue today. Changing the engine inside your app.json can help you get debugger working:

`"jsEngine" : "jsc"`

**Comment by TheElmo** [comment] 2023-03-06 12:51
@jhen0409 Are there plans to look into this?

**Comment by codiku-dev** [comment] 2023-03-06 13:42
Indeed **"jsEngine" : "jsc"**  in app.json is going to work, but hermes is a great improvement, so we need a way to be able to use rnd even with hermes

**Comment by irumiantcev** [comment] 2023-03-14 22:29
`"jsEngine" : "jsc"` doesn't work with iOS simulator. So we have only one opportunity to run Debugger with Android simulator.

**Comment by about-coding** [comment] 2023-03-15 14:10
`"jsEngine": "jsc"` worked for me after running `npx expo start --localhost`. Important to use the --localhost flag

**Comment by irumiantcev** [comment] 2023-03-15 21:01
> `"jsEngine": "jsc"` worked for me after running `npx expo start --localhost`. Important to use the --localhost flag

you have no ability to switch `jsEngine` property in expo46 for iOS. Only for Android. So, `--localhost` flag will not help.

**Comment by about-coding** [comment] 2023-03-16 08:11
I see. I've upgraded to SDK 48 and it's possible also for iOS

**Comment by surya9901** [comment] 2023-03-16 12:57
> I too had this issue today. Changing the engine inside your app.json can help you get debugger working:
> 
> `"jsEngine" : "jsc"`

I tried this but still it's not working for me. Pls correct me if I am wrong.

React and RN version:

"react": "18.2.0",
"react-native": "0.71.4",


<img width="1062" alt="Screenshot 2023-03-16 at 6 19 30 PM" src="https://user-images.githubusercontent.com/44394357/225623289-2cb6c290-f0f4-4996-84fa-9852d1eac85c.png">
<img width="1111" alt="Screenshot 2023-03-16 at 6 19 06 PM" src="https://user-images.githubusercontent.com/44394357/225623297-527deb2d-f88e-47c6-9f18-c8cc32b67d50.png">
<img width="268" alt="debugger issue" src="https://user-images.githubusercontent.com/44394357/225623349-23e506e9-40d6-43e8-8812-7e988defac79.png">

**Comment by Slapbox** [comment] 2023-04-06 21:49
Duplicate of #573?

**Comment by JameFreshket** [comment] 2023-04-25 11:28
Any update?

**Comment by gusgard** [comment] 2023-05-03 23:53
I created a package to solve this issue

```js
yarn add react-native-devsettings
```
```js
import 'react-native-devsettings';
```

basically, it is doing `NativeModules.DevSettings.setIsDebuggingRemotely(true);`
https://www.npmjs.com/package/react-native-devsettings?activeTab=readme

**Comment by jaexplorer** [comment] 2023-05-04 00:15
@gusgard trying now

**Comment by jaexplorer** [comment] 2023-05-04 00:18
@gusgard Omg I love you this works.

**Closed** 2023-05-04 07:35 UTC

**Comment by ilyausorov** [comment] 2023-08-12 00:11
> @gusgard Omg I love you this works.

Came in to say this too

**Comment by NathanNovak** [comment] 2024-04-03 23:53
@gusgard Thanks so much for this!

**Comment by rahul-sysquare** [comment] 2025-07-11 14:16
> I created a package to solve this issue
> 
> yarn add react-native-devsettings
> import 'react-native-devsettings';
> basically, it is doing `NativeModules.DevSettings.setIsDebuggingRemotely(true);` https://www.npmjs.com/package/react-native-devsettings?activeTab=readme

Thanks man. You saved my day. I was struggling whole day and this worked like a charm. I was having issue with iOS Physical device. I was able to hot reload but Debug Js Remote option was missing from Dev Menu. How we can do it manually?

**Comment by NathanNovak** [comment] 2025-07-11 15:50
> > I created a package to solve this issue
> > yarn add react-native-devsettings
> > import 'react-native-devsettings';
> > basically, it is doing `NativeModules.DevSettings.setIsDebuggingRemotely(true);` https://www.npmjs.com/package/react-native-devsettings?activeTab=readme
> 
> Thanks man. You saved my day. I was struggling whole day and this worked like a charm. I was having issue with iOS Physical device. I was able to hot reload but Debug Js Remote option was missing from Dev Menu. How we can do it manually?

Does this work for RN 0.79+?

**Comment by Harshitmal333** [comment] 2025-07-21 12:18
@gusgard  I have tired in RN .76.9 Version its not working.

Getting this error
 TypeError: Cannot read property 'setIsDebuggingRemotely' of null

Any other possible solution for debugging in RN for networking ?
