### ISSUE TITLE
Install under windows 10

### ISSUE THREAD

**Issue by cubeur** [jhen0409/react-native-debugger#403] opened 2019-09-13 00:52 UTC
React Native Debugger app version: [10.0]
Operating System: [Windows 10]

Could you tell me which EXE i must install on my windows please ?

react-native-debugger-0.10.0-setup.exe
or
unzip  rn-debugger-windows-x64.zip   and start the EXE in ?

both of them do nothing, execpt the "setup.exe" which have the install wheal and.. nothing

how can i start the program please ?
Thanks a lot

**Comment by Fl4zher** [comment] 2019-09-19 08:53
Same issue on Windows 10

**Comment by arpitparmar5739** [comment] 2019-09-20 15:48
Getting the same issue on my install on Windows 10!

**Comment by jhen0409** [comment] 2019-09-22 03:18
This issue should resolved by version [0.10.1](https://github.com/jhen0409/react-native-debugger/releases/tag/v0.10.1). I've tested on a Windows 10 VM.

**Closed by jhen0409** 2019-09-22 03:18 UTC

**Comment by RomuloDevelop** [comment] 2019-09-26 19:19
The issue isn't resolved, i experience it with the last update too

**Comment by fmflame** [comment] 2019-10-01 14:15
Same Issue here with 0.10.1. @jhen0409 Reopen the issue and fix it please, lost 3 hours wondering how there can be an app that's not even installing lol! @cubeur Thanks for the hint, 0.9.14 does work!

**Comment by info-house-by** [comment] 2019-10-03 18:09
can't install or launch from zip copy also

**Comment by lucas-wilmart** [comment] 2019-11-15 14:01
Still experiencing the issue. The app works perfectly fine on MacOS but I when I launch the exe both ways (.exe and .zip), I see a window displaying "Installing" (or something like that) and then nothing.
Could you please try to solve the issue once in for all ? I really enjoy working with your app on my office's Mac but can't use it at home with my personnal labtop (windows 10).

**Comment by bearbytes** [comment] 2019-11-21 18:50
I'm having the same problem with current version (0.10.4) on Windows 10.
Installing 0.9.14 works though, so I guess I'm using this for now.

**Comment by jakewtaylor** [comment] 2019-11-25 11:44
+1 This is not resolved, same issue on v0.10.5 on Windows 10

**Comment by RikScheffer** [comment] 2020-01-03 12:42
the beta of version 0.11 does work on windows! To bad we have to wait for react native 0.62 to be officially released
