### ISSUE TITLE
React native debugger does not open while having windows 10 dark theme enabled

### ISSUE THREAD

**Issue by tchanias** [jhen0409/react-native-debugger#493] opened 2020-04-08 07:57 UTC
This happened to me yesterday. I was trying to open react-native-debugger on my desktop but the app was just running in the background and never opened after many times of killing and restarting it.
I thought it was weird since i had no problem running it on my laptop a few days before that. After some searching i found a comment in a forum (i don't remember where exactly) that suggested to try and disable windows 10 dark theme. After i did the app was running normally.

I don't think this is an issue that needs immediate attention, i just couldn't find any related issue ticket here so i thought it would be ok to let you know , just in case you didn't know about it already.  If a similar issue ticket exists , i am sorry in advance for missing it.

**Comment by jhen0409** [comment] 2020-04-08 11:19
Duplicate of #459.

**Closed by jhen0409** 2020-04-08 11:19 UTC
Labels: duplicate
