### ISSUE TITLE
Impossible to debug application on start

### ISSUE THREAD

**Issue by mmavko** [jhen0409/react-native-debugger#315] opened 2019-02-08 12:24 UTC
If I want to debug some code right on the application start (for example `componentDidMount` of main app component, or redux store configuration code) I put a breakpoint and reload my app.

But after that debugger gets reloaded too and it gets loaded much later than the app (so the starting code is already executed). Also breakpoints get lost.

In official debugger this works as expected.

React Native Debugger app version: 0.9.3
React Native version: 0.57.5
Platform: Android
Is real device of platform: Yes
Operating System: macOS

**Comment by jhen0409** [comment] 2019-02-09 09:11
Duplicate of #239.

**Closed by jhen0409** 2019-02-09 09:11 UTC
