### ISSUE TITLE
Debugger crashes getting more frequent

### ISSUE THREAD

**Issue by Jacky9425** [jhen0409/react-native-debugger#414] opened 2019-10-17 01:52 UTC
Earlier this year, the debugger sometimes crashes (No idea when, normally it crashes when app refreshes)

Then Im getting more crashes for every refreshes (2-3 times out of 10 refreshes).

Even though i can resolve it my toggling the debugging tools off and on again. But it is very troublesome as sometimes when i focuses too much on codes and the crashes makes me think that some code modifications freezes the app, which is not, it was the debugger crashes and app freezes.

Please have a look in the problem and try to minimise it , thanks

**Comment by jhen0409** [comment] 2019-10-20 07:05
Duplicate of #405.

**Closed by jhen0409** 2019-10-20 07:05 UTC
