### ISSUE TITLE
TypeError: Cannot read property 'forEach' of undefined

### ISSUE THREAD

**Issue by vishnuc** [jhen0409/react-native-debugger#586] opened 2021-04-25 20:23 UTC
React Native Debugger app version: 0.11.7
React Native version: 0.63.4
Platform: Android simbulator
Is real device of platform: No
Operating System: macOS

Hi , I am just installing basic app via expo using 

`expo init my-app `

Then  I installed react-native-debugger and connected to the port 19000.

When I click any elements  via Devtools I get following error 

```
React DevTools] Error calling listener {event: "inspectElement", payload: {…}}
RemoteConsole.js:80 error: TypeError: Cannot read property 'forEach' of undefined
    at mergeInspectedPaths (backend.js:10860)
    at Object.inspectElement (backend.js:10983)
    at backend.js:12556
    at Bridge.emit (backend.js:5496)
    at backend.js:13211
    at backend.js:15406
    at Array.forEach (<anonymous>)
    at EventTarget.handleMessage (backend.js:15404)
    at EventTarget.dispatchEvent (event-target-shim.js:818)
    at WebSocket.js:231
ExceptionsManager.js:179 TypeError: Cannot read property 'forEach' of undefined
    at mergeInspectedPaths (backend.js:10860)
    at Object.inspectElement (backend.js:10983)
    at backend.js:12556
    at Bridge.emit (backend.js:5496)
    at backend.js:13211
    at backend.js:15406
    at Array.forEach (<anonymous>)
    at EventTarget.handleMessage (backend.js:15404)
    at EventTarget.dispatchEvent (event-target-shim.js:818)
    at WebSocket.js:231
```

Please check attached image

![Screenshot 2021-04-26 at 1 51 07 AM](https://user-images.githubusercontent.com/2216842/116008404-fccf8980-a631-11eb-9be2-550a96a060d2.png)

**Comment by noopurphalak** [comment] 2021-04-26 04:24
Duplicate of https://github.com/jhen0409/react-native-debugger/issues/584

**Closed** 2021-05-02 01:23 UTC
Labels: duplicate
