### ISSUE TITLE
Regular app freeze

### ISSUE THREAD

**Issue by jbburf** [jhen0409/react-native-debugger#412] opened 2019-10-14 20:00 UTC
**Bug Description:** When using RND as my debugging tool, I consistently have to quit the application and relaunch it. Every couple of hours the Electron app freezes (screenshot below) and stops responding to the physical device or simulator (depending on how I am running the app). I have not yet been able to reproduce this behavior, but it happens consistently every day after a few hours of development.

![Screenshot 2019-10-14 13 22 54](https://user-images.githubusercontent.com/6198892/66779107-0d2a7400-ee93-11e9-8f07-924be4bd2271.png)

React Native Debugger app version: 0.10.1
React Native version: 0.60.5
Platform: iOS, Android
Is real device of platform: Real and Simulation
Operating System: MacOS 10.14.6, 10.15 beta and 10.15

**Comment by e1ferapontov** [comment] 2019-10-16 16:14
that's because the devtools pane has crashed as can be seen on your screenshot. it happens to me as well on a regular basis. instead of relaunching the app you can just press `CMD + OPTION + I` twice to relaunch devtools pane

**Comment by SaundersB** [comment] 2019-10-16 18:10
I have this same issue after updating recently

**Comment by jhen0409** [comment] 2019-10-18 02:43
Duplicate of #405.

**Closed by jhen0409** 2019-10-18 02:43 UTC
