### ISSUE TITLE
debugger can't run anymore. And show "DevTools v3 is incompatible with this version of React"

### ISSUE THREAD

**Issue by satsuya0114** [jhen0409/react-native-debugger#484] opened 2020-03-31 02:50 UTC
React Native Debugger app version: [v0.10.7]
React Native version: [0.32.0]
React version: [16.11.0]
Platform: [IOS]
Is real device of platform: [No]
Operating System: [MacOS]

Recently, react-devtools was [migrated to react project](https://github.com/facebook/react-devtools)

I created a new project through react-native cli (npx react-native init projectName) and want to use react-native-debugger today, and my debugger show this msg. 

"
DevTools v3 is incompatible with this version of React

Upgrade to the latest React DevTools:

npm install -d react-devtools
"

I installed react-devtools in my project, but the debugger still not working

How should I do ?

**Comment by jhen0409** [comment] 2020-03-31 03:36
Duplicate of #483.

**Closed by jhen0409** 2020-03-31 03:36 UTC
Labels: duplicate
