### ISSUE TITLE
react-native.debugger imcompatible with react-native-reanimated

### ISSUE THREAD

**Issue by tastafur** [jhen0409/react-native-debugger#626] opened 2021-07-03 16:33 UTC
Hello,

I was studying react-native-reanimated and discovered that by using ui-thread for animations and not the js-thread, it is not compatible and it cannot be debugged with what I like this library and it can only be done with "flipper "

<img width="984" alt="Captura de pantalla 2021-07-03 a las 18 24 05" src="https://user-images.githubusercontent.com/11853181/124360859-5fde2d80-dc2c-11eb-8ba0-af45568087da.png">

https://github.com/software-mansion/react-native-reanimated/issues/1663#issuecomment-770769922

React Native Debugger app version: 0.11.9
React Native version: All versions
Platform: iOS, Android
Is real device of platform: Yes
Operating System: macOS

**Comment by jhen0409** [comment] 2021-07-03 21:49
Duplicate of #573.

**Closed by jhen0409** 2021-07-03 21:49 UTC
Labels: duplicate

**Comment by minhchienwikipedia** [comment] 2021-11-18 07:39
Let's try [this](https://github.com/jhen0409/react-native-debugger/issues/573?fbclid=IwAR3Sjsn5u24SG5pVBCd7_PEc483Cm2v91BkiDAcWwnlytDp-6tOanJmVDIg#issuecomment-972610608)
