### ISSUE TITLE
Cannot see the inspector

### ISSUE THREAD

**Issue by jp928** [jhen0409/react-native-debugger#41] opened 2017-02-03 06:25 UTC
In the first load, the screen always shows a error as below:
<img width="371" alt="screen shot 2017-02-03 at 5 21 58 pm" src="https://cloud.githubusercontent.com/assets/659612/22581606/799807d4-ea35-11e6-8fe4-4af48d3060c5.png">

After pressing the 'Dismiss' button at the left bottom of the screen, the debugger can be used properly in some extent. However, the inspector show up a connecting forever and I am not able to inspect any component from the screen.

<img width="731" alt="screen shot 2017-02-03 at 5 21 38 pm" src="https://cloud.githubusercontent.com/assets/659612/22581640/c12bd044-ea35-11e6-9174-937cae3871b8.png">

**Comment by jhen0409** [comment] 2017-02-04 11:15
Thanks for report! Could you provide a small RN example, let me try to reproduce it?

If you want help to debug, you can just run [electron part of react-devtools](https://github.com/facebook/react-devtools/tree/rndebugger/shells/electron).

**Comment by kanekotic** [comment] 2017-02-08 20:22
@jhen0409 it has been hapening for me also for the last months or so. My react native version is currently 0.40. any ideas or any specific way we can provide data that could be helpful for you?

**Comment by kanekotic** [comment] 2017-02-08 20:24
The other information i can provide is thatvi am using react native logger package so i can see on the console all my redux state changes.

**Comment by jp928** [comment] 2017-02-08 20:29
@jhen0409  Thanks for your reply.
My RN component structure is something like below:

<View style={Styles.container}>
        <Animated.View style={[Styles.headerWrapper, { height }]}>
          <Animated.Image
            source={require('./img/background.png')}
            style={[Styles.backgroundImage, { height }]}
          >
            {this.renderFullHeader()}
            {this.renderstrippedHeader()}
          </Animated.Image>
        </Animated.View>
        <ScrollView
          ref={(ref) => { this.scrollView = ref; }}
          showsVerticalScrollIndicator
          horizontal={false}
          onScroll={e => this.handleScroll(e)}
          onScrollEndDrag={e => this.onScrollEnd(e)}
          scrollEventThrottle={50}
        >
          <Animated.View style={transform}>
            <Text style={{ height: 80, backgroundColor: 'green' }}>First View Goes Here.</Text>
            <Text style={{ height: 600, backgroundColor: 'yellow' }}>Second View Goes Here.</Text>
            <Text style={{ height: 600, backgroundColor: 'red' }}>Third View Goes Here.</Text>
          </Animated.View>
        </ScrollView>
      </View>

**Comment by jp928** [comment] 2017-02-08 20:40
@jhen0409 BTW. The link for electron part of react-devtools is not accessible.

**Comment by jhen0409** [comment] 2017-02-09 17:37
> My RN component structure is something like below:

I can't reproduce the problem with the code (RN v0.39 ~ v0.41), would be better if you can make small project as a GitHub repo for reproduce the problem. @jp928 @kanekotic

> BTW. The link for electron part of react-devtools is not accessible.

Sorry I wrote a wrong link 😅, it should be [here](https://github.com/facebook/react-devtools/tree/master/packages/react-devtools). If you can reproduce this problem with the package, lets move this issue to [react-devtools](https://github.com/facebook/react-devtools).

**Comment by jhen0409** [comment] 2017-02-10 17:03
It seems fixed in [this commit](https://github.com/facebook/react-devtools/commit/59508f6bdf2ae49420a0c6e281090b57e043570c), RNDebugger should used older commit, sorry about that I'll release new version. 😅

**Comment by jhen0409** [comment] 2017-02-14 09:14
`v0.5.6` is released! @jp928 @kanekotic let me know if it still not work.

**Closed by jhen0409** 2017-02-14 09:14 UTC
Labels: bug
