### ISSUE TITLE
Android App gets stuck while running react native debugger

### ISSUE THREAD

**Issue by Raven11** [jhen0409/react-native-debugger#49] opened 2017-02-27 06:41 UTC
React Native version: 0.39.2
Platform: Android
Is real device of platform: Yes
Operating System: Linux

-While debugging android application, app gets stuck often. Mostly, if we are using react native listview.
-Tried increasing the memory of the device, but it also doesn't work. 
-Same application works fine with debugger on IOS platform.

**Comment by hasanmumin** [comment] 2017-02-27 07:40
i have the same issue after update.

**Comment by jhen0409** [comment] 2017-02-27 07:53
Thanks for report! could you provide a small example let me reproduce it?

@hasanmumin are you using `v0.6.0-beta2`? Or just auto-updated to `v0.5.6`?

**Comment by hasanmumin** [comment] 2017-02-27 07:56
@jhen0409 i just updated to v0.5.6

**Comment by gustavjf** [comment] 2017-04-04 07:51
@Raven11 Just out of curiosity, did you notice this while debugging with `react-native-debugger` "out-of-screen"? I noticed when debugging on Android (physical device in my case), navigations and animation transitions (using `react-native-router-flux`) are extremely slow and in some cases, the app is completely unresponsive *until* I move `react-native-debugger` back into screen view.

**Comment by jhen0409** [comment] 2017-06-29 02:07
Close this because no more information provided for a long time. Please try the new version (0.7.1), it solved more problems.

**Closed by jhen0409** 2017-06-29 02:07 UTC
Labels: more-information-needed

**Comment by pencilcheck** [comment] 2017-10-20 18:42
Still doesn't work for me with the latest version and RN0.47. Android app stuck when the debugger is on.

**Comment by kinotto** [comment] 2018-05-08 10:55
same issue here

**Comment by badrshs** [comment] 2018-07-27 09:43
same issue here , I have react-native 0.55.4 fresh project 

and when i start debugging , the browser start loading then it crash 


```
 "dependencies": {
    "native-base": "^2.7.2",
    "react": "16.3.1",
    "react-native": "0.55.4",
    "react-navigation": "^2.9.3"
  },
  "devDependencies": {
    "babel-jest": "23.4.0",
    "babel-preset-react-native": "4.0.0",
    "jest": "23.4.1",
    "react-test-renderer": "16.3.1"
  },
  "jest": {
    "preset": "react-native"
  }
```


emulator error : 
```
Unable to connect with remote debugger

Timeout while connecting to remote debugger
onFailure
    DevSupportManagerImpl.java:1031
onFailure
    WebsocketJavaScriptExecutor.java:83
run
    WebsocketJavaScriptExecutor.java:142
handleCallback
    Handler.java:789
dispatchMessage
    Handler.java:98
loop
    Looper.java:164
main
    ActivityThread.java:6541
invoke
    Method.java
run
    Zygote.java:240
main
    ZygoteInit.java:767


```


I can't update to 0.56 because .56 has an issue on windows
