### ISSUE TITLE
Network inspect not working in react native debugger 0.9.9 for window OS only

### ISSUE THREAD

**Issue by vikrantkalekar** [jhen0409/react-native-debugger#356] opened 2019-06-10 05:16 UTC
Getting below error while enabling network inspect:

Uncaught Error: unsupported BodyInit type
    at Response.Body._initBody (D:\yagna\mobile\node_modules\react-native\Libraries\vendor\core\whatwg-fetch.js:279)
    at new Response (D:\yagna\mobile\node_modules\react-native\Libraries\vendor\core\whatwg-fetch.js:450)
    at XMLHttpRequest.xhr.onload (D:\yagna\mobile\node_modules\react-native\Libraries\vendor\core\whatwg-fetch.js:500)
-->

React Native Debugger app version: [FILL THIS OUT]
React Native version: [FILL THIS OUT]
Platform: [FILL THIS OUT: iOS, Android, ...]
Is real device of platform: [Yes or No]
Operating System: [FILL THIS OUT: macOS, Linux, Windows]

**Comment by jhen0409** [comment] 2019-06-12 10:14
Duplicate of #209.

**Closed by jhen0409** 2019-06-12 10:14 UTC
